import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import MarqueeHeadLine from "@/components/MarqueeHeadLine";

const notoSerifBengali = Noto_Serif_Bengali({
    subsets: ["latin", "bengali"],
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html lang="en" data-theme='bazardor' className={`${notoSerifBengali.className} h-full antialiased`}>

            <body className="min-h-full flex flex-col">
                <Header />
                <MarqueeHeadLine />
                <main className="max-w-6xl py-8 px-4 lg:px-0 w-full mx-auto bg-base-300 space-y-10">
                    {children}
                </main>
            </body>

        </html>
    );
}
